export const BARANGAYS = [
    "A. Bonifacio-Caguioa-Rimando (ABCR)",
    "Abanao-Zandueta-Kayong-Chugum-Otek (AZKCO)",
    "Alfonso Tabora",
    "Ambiong",
    "Andres Bonifacio",
    "Asin Road",
    "Atok Trail",
    "Aurora Hill Proper",
    "Bagong Lipunan",
    "Bakakeng Central",
    "Bakakeng Norte Sur",
    "Balsigan",
    "Bayan Park Village",
    "BGH Compound",
    "Brookside",
    "Brookspoint",
    "Burnham - Legarda",
    "Cabinet Hill - Teacher's Camp",
    "Camdas Subdivision",
    "Camp 7",
    "Camp 8",
    "Camp Allen",
    "Campo Filipino",
    "City Camp Central",
    "City Camp Proper",
    "Country Club Village",
    "Cresencia Village",
    "Dizon Subdivision",
    "Dominican Hill - Mirador",
    "Dontogan",
    "DPS Compound",
    "East Bayan Park",
    "East Modern Site",
    "East Quirino Hill",
    "Engineers' Hill",
    "Fairview Village",
    "Ferdinand",
    "Fort del Pilar - PMA",
    "Gabriela Silang",
    "GEFA (General Emilio F. Aguinaldo)",
    "Gibraltar",
    "Greenwater Village",
    "Guisad Central",
    "Guisad Sorong",
    "Happy Hollow",
    "Happy Homes",
    "Harrison - Claudio Carantes",
    "Hillside",
    "Holy Ghost Extension",
    "Holy Ghost Proper",
    "Honeymoon",
    "Imelda R. Marcos",
    "Imelda Village",
    "Irisan",
    "Kabayanihan",
    "Kagitingan",
    "Kayang - Hilltop",
    "Kayang Extension",
    "Kias",
    "Loakan Apugan",
    "Loakan Liwanag",
    "Loakan Proper",
    "Lopez Jaena",
    "Lourdes Subdivision Extension",
    "Lourdes Subdivision Proper",
    "Lower Dagsian",
    "Lower General Luna",
    "Lower Lourdes Subdivision",
    "Lower Magsaysay",
    "Lower Quirino Hill",
    "Lower Rock Quarry",
    "Lualhati",
    "Lucnab",
    "M. Roxas (Manuel A. Roxas)",
    "Magsaysay Private Road",
    "Malcolm Square - Perfecto",
    "Marcoville",
    "Middle Quezon Hill",
    "Middle Quirino Hill",
    "Middle Rock Quarry",
    "Military Cut-off",
    "Mines View Park",
    "MRR - Queen of Peace",
    "New Lucban",
    "North Central Aurora Hill",
    "North Sanitary Camp",
    "Outlook Drive",
    "Pacdal",
    "Padre Burgos",
    "Padre Zamora",
    "Palma - Urbano",
    "Phil-Am Compound",
    "Pinget",
    "Pinsao Pilot Project",
    "Pinsao Proper",
    "Poliwes",
    "Pucsusan",
    "Quezon Hill Proper",
    "Rizal Monument Area",
    "Saint Joseph Village",
    "Salud Mitra",
    "San Antonio Village",
    "San Luis Village",
    "San Roque Village",
    "San Vicente",
    "Santa Escolastica",
    "Santo Niño Slaughter Compound",
    "Santo Rosario",
    "Santo Tomas Proper",
    "Santo Tomas School Area",
    "Scout Barrio",
    "Session Road Area",
    "SLU-SVP Housing Village",
    "South Central Aurora Hill",
    "South Drive",
    "South Sanitary Camp",
    "Teodora Alonzo",
    "Trancoville",
    "Upper Dagsian",
    "Upper General Luna",
    "Upper Magsaysay",
    "Upper Market Subdivision",
    "Upper QM (Quirino-Magsaysay)",
    "Upper Quezon Hill",
    "Upper Rock Quarry",
    "Victoria Village",
] as const;